feat: Create command line interface for a migrate command
lars-reimann/api-editor pull request #1109
Opened 2022-11-05 13:24 UTC by Aclrian

Closes #1108.

### Summary of Changes

Created a migrate cli command, that takes two api files, an annotation file, and an output path as input

### Testing Instructions

Run Terminal with `parse-package migrate -a1 apiv1.json -a2 apiv2.json -a annotations.json -o out`

2022-11-05 13:48 UTC, Aclrian commented
Still needs smoke tests. Is the naming of the arguments ok? Another '-a' exists in the annotations command, which is for the api.

2022-11-07 22:08 UTC, lars-reimann commented on package-parser/README.md
> +    parse-package migrate parse-package migrate -a1 data/api/sklearn__api.json -a2 data/api/sklearn__apiv2.json -a data/annotations/annotations.json -o out
Duplicate `parse-package migrate`

2022-11-07 22:09 UTC, lars-reimann requested changes
One minor change required.

2022-11-09 08:30 UTC, lars-reimann approved these changes

2022-11-09 08:31 UTC, merged