feat: `api` command should extract source code of api elements
lars-reimann/api-editor pull request #1111
Opened 2022-11-07 12:07 UTC by Aclrian

Closes #1106.

### Summary of Changes
added an attribute `code` to functions and classes that contain the unformatted source code of the function or class

### Testing Instructions

run `package.parser api -p sklearn -o ./out` and compare the output with the original file that the element contains.
`package-parser annotations -a ../data/api/sklearn__api.json -u ../data/usages/sklearn_usages_counts.json -o ./out/annotations.json` can verify that no error occur if the file is loaded.

2022-11-07 22:04 UTC, lars-reimann commented
> * Does it need tests?

A function like `trim_code` should have tests. However, in this case you might be able to simplify the code by using the [`as_string`](https://pylint.pycqa.org/projects/astroid/en/latest/api/base_nodes.html#astroid.nodes.NodeNG.as_string) method of astroid.

> * Should the data folder be updated? (regarding the [BSD 3-Clause "New" or "Revised" License](https://github.com/scikit-learn/scikit-learn/blob/main/COPYING) from scikit-learn)

For the sake of easy (manual) testing, it makes sense to update the data folder. Just include the license file from scikit-learn as well in the `data/api` folder.

2022-11-08 18:29 UTC, Aclrian commented
> However, in this case you might be able to simplify the code by using the [as_string](https://pylint.pycqa.org/projects/astroid/en/latest/api/base_nodes.html#astroid.nodes.NodeNG.as_string) method of astroid.

I compared output of the alternatives and found out that the as_string method ignores comments in the code, but it includes decorators. With a change from fromlineno to lineno decorators would be visible at the current process. Also, it seems that as_string() rearrange lines by removing comments. 

Original `sklearn.datasets._base.load_boston`'s last lines:

```
    return Bunch(
        data=data,
        target=target,
        # last column is target value
        feature_names=feature_names[:-1],
        DESCR=descr_text,
        filename=data_file_name,
        data_module=DATA_MODULE,
    )
```

and what as_string() converts it to:

```
    return Bunch(data=data, target=target, feature_names=feature_names[:-1], DESCR=descr_text, filename=data_file_name, data_module=DATA_MODULE)
```

If the comment line were removed in a new version, there would be a few new lines when we change to as_string().
So, I think we should keep the current procedure.

2022-11-09 10:09 UTC, lars-reimann commented
Let's discuss this tomorrow.

2022-11-10 09:37 UTC, lars-reimann requested changes

2022-11-10 09:37 UTC, lars-reimann commented on data/api/LICENSE
> +BSD 3-Clause License
File should be renamed to something like `scikit-learn license`.

2022-11-10 09:37 UTC, lars-reimann commented on package-parser/package_parser/processing/api/_ast_visitor.py
> +        code = ""
Maybe extract this duplicate code to another function.

2022-11-10 09:37 UTC, lars-reimann commented on package-parser/tests/processing/api/test_get_code_for_api_element.py
> +            """
Might be worth adding a function like [`trim_margin`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/trim-margin.html) to make it clear which whitespace is relevant for the test, and which isn't.

2022-11-11 13:09 UTC, lars-reimann commented
Please resolve conversations yourself once you are done with them.

2022-11-16 12:48 UTC, lars-reimann approved these changes

2022-11-16 12:50 UTC, merged