feat: 433 Creates a Dict from a given json List
lars-reimann/api-editor pull request #437
Opened 2022-04-08 15:23 UTC by jofaul

Closes #433.

### Summary of Changes

New class and package to generate the annotations dict for a given file (path), given that the file is a json file that contains a list of unused sklearn functions or classes. This dict is to be used in #436.

### Testing instructions

Test classes were written, just run them. Further Testing can be done with help of the json file from #436 and the API-editor Client itself (import the json and test if it added annotations are correct).

2022-04-08 15:44 UTC, jofaul commented
@lars-reimann der eine Test schlägt fehl, weil wir da eine Datei lesen wollen die nicht gefunden wird - gibt es eine Möglichkeit den Test erfolgreich laufen zu lassen? @Aclrian wenn du noch eine Idee hast probiers gerne :D

2022-04-08 15:44 UTC, jofaul commented
@lars-reimann der eine Test schlägt fehl, weil wir da eine Datei lesen wollen die nicht gefunden wird - gibt es eine Möglichkeit den Test erfolgreich laufen zu lassen? @Aclrian wenn du noch eine Idee hast probiers gerne :D

2022-04-17 17:29 UTC, GideonKoenig requested changes

2022-04-17 17:29 UTC, GideonKoenig commented on package-parser/package_parser/commands/generate_annotations/_generate_unused_annotations.py
> +    newname = "sklearn/" + parts[0]
Sollte spaeter natuerlich nicht mit "skylearn" gehardcoded werden, aber da die Funktion sowieso noch integriert werden muss, sollte das hier okay sein.

2022-04-17 17:29 UTC, GideonKoenig commented on package-parser/package_parser/commands/generate_annotations/_generate_unused_annotations.py
> +import argparse
Wird wenn ich das richtig sehe nicht verwendet. Sollte also entfernt werden.

2022-04-17 17:29 UTC, GideonKoenig commented on package-parser/tests/commands/generate_annotations/test_generate_unused_annotations.py
> +    )
Hier wird zwei mal das selbe getestet. Ich nehme an, hier sollten eigentlich verschiedene Eingaben verwendet werden. Ansonsten eine der beiden Funktionen entfernen.

2022-04-17 17:29 UTC, GideonKoenig commented on package-parser/tests/commands/generate_annotations/unused_functions_list.json
> +]
Gehoert natuerlich eigentlich nicht ins Repo. Kann aber erstmal hier bleiben und dann spaeter beim integrieren von der Funktion in den Programmablauf entfernt werden, da sie dann nicht mehr notwendig sein wird.

2022-04-18 11:20 UTC, lars-reimann commented on package-parser/.gitignore
> +.idea/
Ist schon in Ordnung, die Ordner zu entfernen und anschließend zu ignorieren. In diesem PR sind allerdings trotzdem Änderungen an den Dateien in `.idea` vorgenommen wurden, die entfernt werden sollten.

2022-04-18 11:22 UTC, lars-reimann commented on package-parser/tests/commands/generate_annotations/test_generate_unused_annotations.py
> +    )
Ist einmal mit `_MiniBatchKMeans` und einal mit `MiniBatchKMeans` (ohne Unterstrich).

2022-04-20 07:42 UTC, GideonKoenig approved these changes

2022-04-20 07:45 UTC, lars-reimann commented
Only suggestion I have would be more user-focused PR titles. "433 Creates a Dict from a given json List" is very technical and does not describe what this PR actually accomplishes.

2022-04-21 12:17 UTC, merged