feat: Automatisierte Herleitung von Boundary Annotations
lars-reimann/api-editor pull request #474
Opened 2022-05-06 12:32 UTC by nvollroth

Closes #445.

### Summary of Changes

### Screenshots (if necessary)

### Testing instructions

2022-05-07 10:58 UTC, Masara approved these changes
Sieht gut aus. Kann an Lars gehen, sobald Testing Instructions hinzugefügt wurden,

2022-05-07 11:08 UTC, lars-reimann commented
Ist das "DO NOT MERGE" noch aktuell?

2022-05-07 11:16 UTC, nvollroth commented
Nein das  "DO NOT MERGE" ist nicht mehr aktuell und kann entfernt werden, sodass der Branch gemergt werden kann.

2022-05-07 11:29 UTC, lars-reimann commented
## Mögliche Probleme

### 1. Falsches "target":
**qname:** sklearn.feature_extraction.text.CountVectorizer.__init__.min_df
**target:** "test/__init__/min_df"

Wird wahrscheinlich bereits gelöst, wenn #449 implementiert wird.

### 2. Falsche Grenze:

In API-Daten:
```json5
"refined_type": {
    "kind": "BoundaryType",
    "base_type": "float",
    "min": 0.5, // <-------------------
    "max": "Infinity",
    "min_inclusive": true,
    "max_inclusive": false
}
```

Erzeugte Annotation:
```json5
"interval": {
  "isDiscrete": false,
  "lowerIntervalLimit": 0.0, // <------------------- (sollte 0.5 sein)
  "lowerLimitType": 0,
  "upperIntervalLimit": "Infinity",
  "upperLimitType": 2
}
```

### 3. `defaultType` Eigenschaft

Bei den Annotationen wird eine zusätzliche Eigenschaft `defaultType` erzeugt. Vergleiche mit [gewünschtet Ausgabe](https://github.com/lars-reimann/api-editor/issues/445#issuecomment-1106457356):
```json5
"test/__init__/min_df": {
  "target": "test/__init__/min_df",
  "defaultType": "float", // <------------------- (sollte entfernt werden)
  "interval": {
    "isDiscrete": false,
    "lowerIntervalLimit": 0.0,
    "lowerLimitType": 0,
    "upperIntervalLimit": "Infinity",
    "upperLimitType": 2
  }
},
```

### 4. Offene Grenzen haben "Infinity" als Wert
Bei offenen Grenzen (`limitType` = 2) sollte das entsprechende `intervalLimit` auf 0 statt "Infinity" gesetzt werden. Mein Fehler, hätte ich früher angeben sollen.

2022-05-07 11:30 UTC, lars-reimann requested changes
## Mögliche Probleme

### 1. Falsches "target":
**qname:** sklearn.feature_extraction.text.CountVectorizer.__init__.min_df
**target:** "test/__init__/min_df"

Wird wahrscheinlich bereits gelöst, wenn #449 implementiert wird.

### 2. Falsche Grenze:

In API-Daten:
```json5
"refined_type": {
    "kind": "BoundaryType",
    "base_type": "float",
    "min": 0.5, // <-------------------
    "max": "Infinity",
    "min_inclusive": true,
    "max_inclusive": false
}
```

Erzeugte Annotation:
```json5
"interval": {
  "isDiscrete": false,
  "lowerIntervalLimit": 0.0, // <------------------- (sollte 0.5 sein)
  "lowerLimitType": 0,
  "upperIntervalLimit": "Infinity",
  "upperLimitType": 2
}
```

### 3. `defaultType` Eigenschaft

Bei den Annotationen wird eine zusätzliche Eigenschaft `defaultType` erzeugt. Vergleiche mit [gewünschtet Ausgabe](https://github.com/lars-reimann/api-editor/issues/445#issuecomment-1106457356):
```json5
"test/__init__/min_df": {
  "target": "test/__init__/min_df",
  "defaultType": "float", // <------------------- (sollte entfernt werden)
  "interval": {
    "isDiscrete": false,
    "lowerIntervalLimit": 0.0,
    "lowerLimitType": 0,
    "upperIntervalLimit": "Infinity",
    "upperLimitType": 2
  }
},
```

### 4. Offene Grenzen haben "Infinity" als Wert
Bei offenen Grenzen (`limitType` = 2) sollte das entsprechende `intervalLimit` auf 0 statt "Infinity" gesetzt werden. Mein Fehler, hätte ich früher angeben sollen.

2022-05-07 12:19 UTC, nvollroth commented
Changes wurden übernommen.

2022-05-07 13:03 UTC, lars-reimann requested changes

2022-05-07 13:03 UTC, lars-reimann commented on package-parser/package_parser/commands/generate_annotations/generate_annotations.py
> +                is_discrete = False
Auch wenn eine Seite des Intervalls offen ist, kann das Intervall diskret sein.

2022-05-07 13:03 UTC, lars-reimann commented on package-parser/package_parser/commands/generate_annotations/generate_annotations.py
> +                is_discrete = False
Auch wenn eine Seite des Intervalls offen ist, kann das Intervall diskret sein.

2022-05-07 13:03 UTC, lars-reimann commented on package-parser/package_parser/commands/generate_annotations/generate_annotations.py
> +            if min_value == "NegativeInfinity":
In diesem Fall `min_value` auf `0` setzen.

2022-05-07 13:03 UTC, lars-reimann commented on package-parser/package_parser/commands/generate_annotations/generate_annotations.py
> +            if max_value == "Infinity":
In diesem Fall `max_value` auf `0` setzen.

2022-05-07 14:07 UTC, lars-reimann commented on package-parser/tests/commands/generate_annotations/test_generate_annotations.py
> +            "upperIntervalLimit": "Infinity",
```suggestion
            "upperIntervalLimit": 0,
```

2022-05-07 14:10 UTC, nvollroth commented
Offene Grenzen werden bei der Bestimmung, ob ein Intervall diskret ist oder nicht, mit berücksichtigt.

2022-05-07 14:20 UTC, lars-reimann requested changes

2022-05-07 14:20 UTC, lars-reimann commented on package-parser/package_parser/commands/generate_annotations/generate_annotations.py
> +        max_value = 0
Argumente werden in Python "by value" übergeben. Die Änderungen an `min_value` und `max_value` sind außerhalb der Funktion nicht sichtbar.

2022-05-07 14:20 UTC, lars-reimann commented on package-parser/package_parser/commands/generate_annotations/generate_annotations.py
> +    return isinstance(min_value, int) and isinstance(max_value, int)
1. Durch die Zuweisung in Zeilen 451 bis 454 wird das Ergebnis verfälscht.
2. In den API Daten steht bereits, ob das Intervall diskret sein soll (base_type == "int") oder nicht (base_type == "float"). Die Grenzen sind nicht relevant dafür, ob das Intervall diskret sein soll oder nicht.

2022-05-08 09:11 UTC, lars-reimann approved these changes

2022-05-08 09:11 UTC, merged